### ISSUE TITLE
error with storage credential

### ISSUE THREAD

**Issue by djouallah** [duckdb/uc_catalog#5]
list tables works fine, but when trying to run a simple query I get this ?  

```
IOException: IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: 's3://xxxxxxxxxxxx: Hit error: 8 (ObjectStoreError) with message (Error interacting with object store: Generic S3 error: Client error with status 403 Forbidden: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>bbbbbbbb</RequestId><HostId>uuuuuu=</HostId></Error>)

```

**Comment by Rafael-Dabrowski** [comment]
Similar Issue here but for Azure: 
`DuckDB.NET.Data.DuckDBException (0x00000001): IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: 'abfss://unity@xxx'): Hit error: 8 (ObjectStoreError) with message (Error interacting with object store: Generic MicrosoftAzure error: Error performing token request: Error after 10 retries in 14.459122295s, max_retries:10, retry_timeout:180s, source:error sending request for url (http://169.254.169.254/metadata/identity/oauth2/token?api-version=2019-08-01&resource=https%3A%2F%2Fstorage.azure.com)

Tested locally and in an Azure Container.

**Comment by IceRhymers** [comment]
https://github.com/duckdb/uc_catalog/blob/main/src/uc_api.cpp#L125

Here in the code is where this extension makes the API call to Unity Catalog to obtain the temporary table credentials for a scan. This endpoint is actually locked down by databricks so you're not authenticated at all. 
<img width="1184" alt="Screenshot 2024-06-14 at 2 29 02 PM" src="https://github.com/duckdb/uc_catalog/assets/84605639/bab5f9ce-667b-4132-9934-5259316e2032">

**Comment by djouallah** [comment]
@IceRhymers the theory is the catalog will provide credentials only for the *files* where you have access already, not to a bucket or folder.

**Comment by djouallah** [comment]
Closing the biug reports as it is a Databricks issue
